# Pre-0.1.0 region names, per atlas, keyed on `label`
#
# Until 0.1.0 the `region` column of the bundled atlases held a long-form
# display name. 0.1.0 re-keyed `region` to a short identifier derived from
# `label` and moved the curated long-form name to `names`. That makes code
# written against the old `region` values silently stop matching, so this
# table records exactly what each atlas shipped, verbatim from the CRAN
# 0.0.4 sources, and `legacy_region_map()` reads it.
#
# `names` is NOT this table. `names` is the curated display name, chosen to
# read well in a figure legend; several of the 0.0.4 `region` values were
# mechanically derived and do not ("ventraldc", "cc posterior"). Keeping the
# two apart is deliberate: one is for people, one is for migration.
#
# `label` is unchanged between 0.0.4 and 0.1.0 for all four atlases, which is
# what lets this table key on it. Where two 0.0.4 regions shared one label
# (aseg's "Thalamus" / "Thalamus Proper") both rows are kept, so both old
# names still translate.
#
# Regenerate with: source("data-raw/legacy_regions.R")

legacy_regions <- list(
  dk = data.frame(
    label = c(
      "lh_bankssts",
      "lh_caudalanteriorcingulate",
      "lh_caudalmiddlefrontal",
      "lh_corpuscallosum",
      "lh_cuneus",
      "lh_entorhinal",
      "lh_frontalpole",
      "lh_fusiform",
      "lh_inferiorparietal",
      "lh_inferiortemporal",
      "lh_insula",
      "lh_isthmuscingulate",
      "lh_lateraloccipital",
      "lh_lateralorbitofrontal",
      "lh_lingual",
      "lh_medialorbitofrontal",
      "lh_middletemporal",
      "lh_paracentral",
      "lh_parahippocampal",
      "lh_parsopercularis",
      "lh_parsorbitalis",
      "lh_parstriangularis",
      "lh_pericalcarine",
      "lh_postcentral",
      "lh_posteriorcingulate",
      "lh_precentral",
      "lh_precuneus",
      "lh_rostralanteriorcingulate",
      "lh_rostralmiddlefrontal",
      "lh_superiorfrontal",
      "lh_superiorparietal",
      "lh_superiortemporal",
      "lh_supramarginal",
      "lh_temporalpole",
      "lh_transversetemporal",
      "rh_bankssts",
      "rh_caudalanteriorcingulate",
      "rh_caudalmiddlefrontal",
      "rh_corpuscallosum",
      "rh_cuneus",
      "rh_entorhinal",
      "rh_frontalpole",
      "rh_fusiform",
      "rh_inferiorparietal",
      "rh_inferiortemporal",
      "rh_insula",
      "rh_isthmuscingulate",
      "rh_lateraloccipital",
      "rh_lateralorbitofrontal",
      "rh_lingual",
      "rh_medialorbitofrontal",
      "rh_middletemporal",
      "rh_paracentral",
      "rh_parahippocampal",
      "rh_parsopercularis",
      "rh_parsorbitalis",
      "rh_parstriangularis",
      "rh_pericalcarine",
      "rh_postcentral",
      "rh_posteriorcingulate",
      "rh_precentral",
      "rh_precuneus",
      "rh_rostralanteriorcingulate",
      "rh_rostralmiddlefrontal",
      "rh_superiorfrontal",
      "rh_superiorparietal",
      "rh_superiortemporal",
      "rh_supramarginal",
      "rh_temporalpole",
      "rh_transversetemporal"
    ),
    legacy_region = c(
      "banks of superior temporal sulcus",
      "caudal anterior cingulate",
      "caudal middle frontal",
      "corpus callosum",
      "cuneus",
      "entorhinal",
      "frontal pole",
      "fusiform",
      "inferior parietal",
      "inferior temporal",
      "insula",
      "isthmus cingulate",
      "lateral occipital",
      "lateral orbitofrontal",
      "lingual",
      "medial orbitofrontal",
      "middle temporal",
      "paracentral",
      "parahippocampal",
      "pars opercularis",
      "pars orbitalis",
      "pars triangularis",
      "pericalcarine",
      "postcentral",
      "posterior cingulate",
      "precentral",
      "precuneus",
      "rostral anterior cingulate",
      "rostral middle frontal",
      "superior frontal",
      "superior parietal",
      "superior temporal",
      "supramarginal",
      "temporal pole",
      "transverse temporal",
      "banks of superior temporal sulcus",
      "caudal anterior cingulate",
      "caudal middle frontal",
      "corpus callosum",
      "cuneus",
      "entorhinal",
      "frontal pole",
      "fusiform",
      "inferior parietal",
      "inferior temporal",
      "insula",
      "isthmus cingulate",
      "lateral occipital",
      "lateral orbitofrontal",
      "lingual",
      "medial orbitofrontal",
      "middle temporal",
      "paracentral",
      "parahippocampal",
      "pars opercularis",
      "pars orbitalis",
      "pars triangularis",
      "pericalcarine",
      "postcentral",
      "posterior cingulate",
      "precentral",
      "precuneus",
      "rostral anterior cingulate",
      "rostral middle frontal",
      "superior frontal",
      "superior parietal",
      "superior temporal",
      "supramarginal",
      "temporal pole",
      "transverse temporal"
    ),
    stringsAsFactors = FALSE
  ),
  aseg = data.frame(
    label = c(
      "Brain-Stem",
      "CC_Anterior",
      "CC_Central",
      "CC_Mid_Anterior",
      "CC_Mid_Posterior",
      "CC_Posterior",
      "Left-Accumbens-area",
      "Left-Amygdala",
      "Left-Caudate",
      "Left-Cerebellum-Cortex",
      "Left-choroid-plexus",
      "Left-Hippocampus",
      "Left-Pallidum",
      "Left-Putamen",
      "Left-Thalamus",
      "Left-Thalamus",
      "Left-VentralDC",
      "Left-vessel",
      "Optic-Chiasm",
      "Right-Accumbens-area",
      "Right-Amygdala",
      "Right-Caudate",
      "Right-Cerebellum-Cortex",
      "Right-choroid-plexus",
      "Right-Hippocampus",
      "Right-Pallidum",
      "Right-Putamen",
      "Right-Thalamus",
      "Right-Thalamus",
      "Right-VentralDC",
      "Right-vessel"
    ),
    legacy_region = c(
      "Brain Stem",
      "cc anterior",
      "cc central",
      "cc mid anterior",
      "cc mid posterior",
      "cc posterior",
      "accumbens area",
      "Amygdala",
      "Caudate",
      "Cerebellum",
      "choroid plexus",
      "Hippocampus",
      "Pallidum",
      "Putamen",
      "Thalamus",
      "Thalamus Proper",
      "ventraldc",
      "vessel",
      "Optic Chiasm",
      "accumbens area",
      "Amygdala",
      "Caudate",
      "Cerebellum",
      "choroid plexus",
      "Hippocampus",
      "Pallidum",
      "Putamen",
      "Thalamus",
      "Thalamus Proper",
      "ventraldc",
      "vessel"
    ),
    stringsAsFactors = FALSE
  ),
  tracula = data.frame(
    label = c(
      "acomm.bbr.prep",
      "cc.bodyc.bbr.prep",
      "cc.bodyp.bbr.prep",
      "cc.bodypf.bbr.prep",
      "cc.bodypm.bbr.prep",
      "cc.bodyt.bbr.prep",
      "cc.genu.bbr.prep",
      "cc.rostrum.bbr.prep",
      "cc.splenium.bbr.prep",
      "lh.af.bbr.prep",
      "lh.ar.bbr.prep",
      "lh.atr.bbr.prep",
      "lh.cbd.bbr.prep",
      "lh.cbv.bbr.prep",
      "lh.cst.bbr.prep",
      "lh.emc.bbr.prep",
      "lh.fat.bbr.prep",
      "lh.fx.bbr.prep",
      "lh.ilf.bbr.prep",
      "lh.mlf.bbr.prep",
      "lh.or.bbr.prep",
      "lh.slf1.bbr.prep",
      "lh.slf2.bbr.prep",
      "lh.slf3.bbr.prep",
      "lh.uf.bbr.prep",
      "mcp.bbr.prep",
      "rh.af.bbr.prep",
      "rh.ar.bbr.prep",
      "rh.atr.bbr.prep",
      "rh.cbd.bbr.prep",
      "rh.cbv.bbr.prep",
      "rh.cst.bbr.prep",
      "rh.emc.bbr.prep",
      "rh.fat.bbr.prep",
      "rh.fx.bbr.prep",
      "rh.ilf.bbr.prep",
      "rh.mlf.bbr.prep",
      "rh.or.bbr.prep",
      "rh.slf1.bbr.prep",
      "rh.slf2.bbr.prep",
      "rh.slf3.bbr.prep",
      "rh.uf.bbr.prep"
    ),
    legacy_region = c(
      "anterior commissure",
      "CC body central",
      "CC body parietal",
      "CC body prefrontal",
      "CC body premotor",
      "CC body temporal",
      "CC genu",
      "CC rostrum",
      "CC splenium",
      "arcuate fasciculus",
      "acoustic radiation",
      "anterior thalamic radiation",
      "cingulum dorsal",
      "cingulum ventral",
      "corticospinal tract",
      "extreme capsule",
      "frontal aslant tract",
      "fornix",
      "inferior longitudinal fasciculus",
      "middle longitudinal fasciculus",
      "optic radiation",
      "SLF I",
      "SLF II",
      "SLF III",
      "uncinate fasciculus",
      "middle cerebellar peduncle",
      "arcuate fasciculus",
      "acoustic radiation",
      "anterior thalamic radiation",
      "cingulum dorsal",
      "cingulum ventral",
      "corticospinal tract",
      "extreme capsule",
      "frontal aslant tract",
      "fornix",
      "inferior longitudinal fasciculus",
      "middle longitudinal fasciculus",
      "optic radiation",
      "SLF I",
      "SLF II",
      "SLF III",
      "uncinate fasciculus"
    ),
    stringsAsFactors = FALSE
  ),
  suit = data.frame(
    label = c(
      "left_CrusI",
      "left_CrusII",
      "left_Dentate",
      "left_Fastigial",
      "left_I_IV",
      "left_Interposed",
      "left_IX",
      "left_V",
      "left_VI",
      "left_VIIb",
      "left_VIIIa",
      "left_VIIIb",
      "left_X",
      "right_CrusI",
      "right_CrusII",
      "right_Dentate",
      "right_Fastigial",
      "right_I_IV",
      "right_Interposed",
      "right_IX",
      "right_V",
      "right_VI",
      "right_VIIb",
      "right_VIIIa",
      "right_VIIIb",
      "right_X",
      "vermis_CrusI",
      "vermis_CrusII",
      "vermis_IX",
      "vermis_VI",
      "vermis_VIIb",
      "vermis_VIIIa",
      "vermis_VIIIb",
      "vermis_X"
    ),
    legacy_region = c(
      "CrusI",
      "CrusII",
      "Dentate",
      "Fastigial",
      "I_IV",
      "Interposed",
      "IX",
      "V",
      "VI",
      "VIIb",
      "VIIIa",
      "VIIIb",
      "X",
      "CrusI",
      "CrusII",
      "Dentate",
      "Fastigial",
      "I_IV",
      "Interposed",
      "IX",
      "V",
      "VI",
      "VIIb",
      "VIIIa",
      "VIIIb",
      "X",
      "CrusI",
      "CrusII",
      "IX",
      "VI",
      "VIIb",
      "VIIIa",
      "VIIIb",
      "X"
    ),
    stringsAsFactors = FALSE
  )
)
